# Generated by Django 4.2.30 on 2026-08-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
